### ISSUE TITLE
Critical Category Manager Bug

### ISSUE THREAD

**Issue by nickramsay** [HotaruCMS/BookmarkingPlugins#4]
Can't add a new category, and since you can't submit a url without creating a category to put it in, bookmarking is impossible. 

A second problem with the Category Manager is that every click returns you to the "Overview" tab instead of the "Settings" tab where all the action is.

**Comment by shibuya246** [comment]
fixed by commit to core which was blocking this action on tab. both issue related to same thing
have made the settings tab default now
